name: Docker Publish on Repository Events

on:
  #pull_request:
  #  branches: [ "main" ]
  #  types:
  #    - "opened"
  #    - "synchronize"
  #    - "reopened"
  #    - "closed"
  push:
    branches: [ "main" ]

jobs:
  detect-changed-images:
    runs-on: ubuntu-latest
    steps:
      - name: Set fetch depth
        id: set_fetch_depth
        run: |
          numCommits=$(echo "${{ toJson(github.event.commits) }}" | jq '. | length')
          depth=$(("$numCommits"+1))
          echo "$depth"
          echo "::set-output name=fetch_depth::${depth}"
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ steps.set_fetch_depth.outputs.fetch_depth }}
      - name: Detect changed images
        id: detect_images
        shell: bash
        run: |
          echo "SHA: ${GITHUB_SHA}"
          echo "ACTOIN: ${{ github.event.action }}"
          echo "MERGED: ${{ github.event.pull_request.merged }}"
          echo "BASE BRANCH: ${GITHUB_BASE_REF}"
          echo "HEAD BRANCH: ${GITHUB_HEAD_REF}"
          echo "BEFORE COMMIT: ${{ github.event.before }}"
          echo "AFTER COMMIT: ${{ github.event.after }}"

          echo "diff 1"
          git diff "${{ github.event.before }}" "${{ github.event.after }}" --name-only
          #echo "diff 2"
          #git diff "origin/${GITHUB_BASE_REF}"..."${GITHUB_HEAD_REF}" --name-only
          #echo "diff 3"
          #git diff "origin/${GITHUB_BASE_REF}"..."${GITHUB_HEAD_REF}" --relative="aaa" --name-only